import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, useScroll, useTransform, AnimatePresence } from 'framer-motion'

// ─── Data ─────────────────────────────────────────────────────────────────────

const DEMO_WORDS = [
  {
    word: 'Ephemeral',
    pronunciation: '/ɪˈfem.ər.əl/',
    part: 'adj.',
    definition: 'Lasting for only a short time; transitory.',
    example: 'The ephemeral nature of cherry blossoms makes them more precious.',
    mnemonic: 'Think "e-FEM-eral" — fleeting like a passing glance.',
  },
  {
    word: 'Perspicacious',
    pronunciation: '/ˌpɜːr.spɪˈkeɪ.ʃəs/',
    part: 'adj.',
    definition: 'Having a ready insight; shrewd and discerning.',
    example: 'Her perspicacious analysis revealed flaws others had missed.',
    mnemonic: 'Per-SPIC — like spectacles, you see things clearly.',
  },
  {
    word: 'Recalcitrant',
    pronunciation: '/rɪˈkæl.sɪ.trənt/',
    part: 'adj.',
    definition: 'Stubbornly resistant to authority or guidance.',
    example: 'The recalcitrant student refused every offer of help.',
    mnemonic: 'RE-cal-CI-trant — re-calculates how to resist.',
  },
  {
    word: 'Sanguine',
    pronunciation: '/ˈsæŋ.ɡwɪn/',
    part: 'adj.',
    definition: 'Optimistic, especially in difficult situations.',
    example: 'She remained sanguine despite the mounting setbacks.',
    mnemonic: 'SANG with joy — always positive, always singing.',
  },
]

const FEATURES = [
  {
    icon: '🧠',
    title: 'Spaced Repetition',
    desc: 'Our algorithm surfaces words exactly when you\'re about to forget them — maximizing retention with minimum effort.',
    color: '#8b1a2e',
  },
  {
    icon: '👹',
    title: 'Boss Battles',
    desc: '10 questions. 20 seconds each. No hearts. Win and claim massive XP. Lose and come back stronger.',
    color: '#c9963a',
  },
  {
    icon: '🔥',
    title: 'Streaks & XP',
    desc: 'Build daily habits through streaks, earn XP for every correct answer, and level up from Beginner to SAT Master.',
    color: '#1D9E75',
  },
  {
    icon: '⚔️',
    title: 'Friend Duels',
    desc: 'Challenge friends to async vocabulary battles. Same words, different scores. May the best mind win.',
    color: '#8b1a2e',
  },
  {
    icon: '💡',
    title: 'AI Mnemonics',
    desc: 'Every word gets a unique memory trick generated by AI — making even the hardest words impossible to forget.',
    color: '#c9963a',
  },
  {
    icon: '📖',
    title: '1,380+ Words',
    desc: 'Built from a curated SAT vocabulary book. Every word that matters, nothing that doesn\'t.',
    color: '#1D9E75',
  },
]

const STEPS = [
  {
    num: '01',
    title: 'Set your level',
    desc: 'Take a quick 5-question placement test or choose your level manually. We start you exactly where you need to be.',
  },
  {
    num: '02',
    title: 'Learn daily',
    desc: 'Short focused sessions mixing flashcards, multiple choice, and fill-in-the-blank. Hit your daily goal, keep your streak.',
  },
  {
    num: '03',
    title: 'Watch scores rise',
    desc: 'Track mastery word by word. Your SAT readiness score updates in real time as you conquer the vocabulary.',
  },
]

const STATS = [
  { value: '1,380+', label: 'SAT Words' },
  { value: '6',      label: 'Exercise Types' },
  { value: '5',      label: 'Mastery Levels' },
  { value: '100%',   label: 'Free to Start' },
]

// ─── Nav ──────────────────────────────────────────────────────────────────────

function Nav({ onCTA }) {
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handler = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', handler)
    return () => window.removeEventListener('scroll', handler)
  }, [])

  return (
    <motion.nav
      initial={{ y: -60, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      style={{
        position: 'fixed', top: 0, left: 0, right: 0,
        zIndex: 100,
        padding: '0 24px',
        height: 64,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: scrolled ? 'rgba(255,255,255,0.95)' : 'transparent',
        backdropFilter: scrolled ? 'blur(12px)' : 'none',
        borderBottom: scrolled ? '1px solid rgba(139,26,46,0.1)' : 'none',
        transition: 'all 0.3s ease',
        maxWidth: 1200, margin: '0 auto',
        width: '100%',
        left: '50%', transform: scrolled ? 'translateX(-50%)' : 'none',
      }}
    >
      {/* Logo */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          width: 36, height: 36, borderRadius: 10,
          background: 'var(--c-primary)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 2px 8px rgba(139,26,46,0.3)',
        }}>
          <span style={{ color: '#fff', fontWeight: 900, fontSize: 18, fontFamily: 'Georgia, serif' }}>V</span>
        </div>
        <span style={{
          fontSize: 20, fontWeight: 800,
          color: scrolled ? 'var(--c-primary)' : '#fff',
          fontFamily: 'Georgia, "Times New Roman", serif',
          letterSpacing: '-0.3px',
          transition: 'color 0.3s ease',
        }}>
          Vocabook
        </span>
      </div>

      {/* CTA */}
      <button
        onClick={onCTA}
        style={{
          padding: '9px 22px',
          background: scrolled ? 'var(--c-primary)' : '#fff',
          color: scrolled ? '#fff' : 'var(--c-primary)',
          border: 'none', borderRadius: 99,
          fontSize: 14, fontWeight: 700,
          cursor: 'pointer',
          boxShadow: scrolled ? '0 2px 8px rgba(139,26,46,0.3)' : 'none',
          transition: 'all 0.3s ease',
        }}
      >
        Get started
      </button>
    </motion.nav>
  )
}

// ─── Hero ─────────────────────────────────────────────────────────────────────

function Hero({ onCTA }) {
  return (
    <section style={{
      minHeight: '100vh',
      background: 'linear-gradient(160deg, #3d0a15 0%, #8b1a2e 45%, #a82236 70%, #5c111e 100%)',
      display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center',
      padding: '100px 24px 80px',
      position: 'relative', overflow: 'hidden',
      textAlign: 'center',
    }}>
      {/* Background orbs */}
      <div style={{
        position: 'absolute', top: '10%', left: '5%',
        width: 400, height: 400, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(201,150,58,0.15) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />
      <div style={{
        position: 'absolute', bottom: '10%', right: '5%',
        width: 500, height: 500, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(255,255,255,0.05) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />

      {/* Floating word chips */}
      {['ephemeral', 'perspicacious', 'sanguine', 'recalcitrant', 'tenacious', 'lucid'].map((w, i) => (
        <motion.div
          key={w}
          initial={{ opacity: 0, y: 20 }}
          animate={{
            opacity: [0, 0.4, 0.4, 0],
            y: [20, 0, 0, -20],
          }}
          transition={{
            duration: 4,
            delay: i * 0.8,
            repeat: Infinity,
            repeatDelay: 4,
          }}
          style={{
            position: 'absolute',
            fontSize: 12, fontWeight: 600,
            color: 'rgba(255,255,255,0.5)',
            background: 'rgba(255,255,255,0.08)',
            border: '1px solid rgba(255,255,255,0.1)',
            padding: '4px 12px', borderRadius: 99,
            top: `${15 + (i % 3) * 25}%`,
            left: i < 3 ? `${3 + i * 6}%` : 'auto',
            right: i >= 3 ? `${3 + (i - 3) * 6}%` : 'auto',
            pointerEvents: 'none',
          }}
        >
          {w}
        </motion.div>
      ))}

      {/* Badge */}
      <motion.div
        initial={{ opacity: 0, scale: 0.8 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2 }}
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: 'rgba(201,150,58,0.2)',
          border: '1px solid rgba(201,150,58,0.4)',
          borderRadius: 99, padding: '6px 16px',
          marginBottom: 28,
        }}
      >
        <span style={{ fontSize: 14 }}>📖</span>
        <span style={{ fontSize: 13, fontWeight: 600, color: '#f0c96a' }}>
          1,380 curated SAT words
        </span>
      </motion.div>

      {/* Headline */}
      <motion.h1
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3, duration: 0.6 }}
        style={{
          fontSize: 'clamp(38px, 8vw, 72px)',
          fontWeight: 900,
          color: '#fff',
          lineHeight: 1.1,
          letterSpacing: '-1.5px',
          fontFamily: 'Georgia, "Times New Roman", serif',
          marginBottom: 20,
          maxWidth: 800,
        }}
      >
        Master every word
        <br />
        <span style={{
          WebkitTextStroke: '2px rgba(255,255,255,0.6)',
          color: 'transparent',
        }}>
          before test day.
        </span>
      </motion.h1>

      {/* Subheadline */}
      <motion.p
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.45 }}
        style={{
          fontSize: 'clamp(16px, 2.5vw, 20px)',
          color: 'rgba(255,255,255,0.7)',
          maxWidth: 520,
          lineHeight: 1.7,
          marginBottom: 40,
        }}
      >
        The gamified vocabulary app built for SAT prep.
        Spaced repetition, boss battles, and AI mnemonics —
        so nothing slips through the cracks.
      </motion.p>

      {/* CTAs */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.55 }}
        style={{ display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center' }}
      >
        <motion.button
          whileHover={{ scale: 1.04, boxShadow: '0 8px 32px rgba(201,150,58,0.4)' }}
          whileTap={{ scale: 0.97 }}
          onClick={onCTA}
          style={{
            padding: '14px 36px', minHeight: 56,
            background: 'var(--c-gold)',
            color: '#fff', border: 'none',
            borderRadius: 99, fontSize: 17, fontWeight: 800,
            cursor: 'pointer',
            boxShadow: '0 4px 20px rgba(201,150,58,0.35)',
            letterSpacing: '0.01em',
          }}
        >
          Start for free →
        </motion.button>
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={onCTA}
          style={{
            padding: '14px 28px', minHeight: 56,
            background: 'rgba(255,255,255,0.1)',
            color: '#fff',
            border: '1.5px solid rgba(255,255,255,0.3)',
            borderRadius: 99, fontSize: 16, fontWeight: 600,
            cursor: 'pointer',
            backdropFilter: 'blur(8px)',
          }}
        >
          Log in
        </motion.button>
      </motion.div>

      {/* Stats row */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
        style={{
          display: 'flex', gap: 'clamp(20px, 5vw, 48px)',
          marginTop: 64, flexWrap: 'wrap', justifyContent: 'center',
        }}
      >
        {STATS.map(({ value, label }) => (
          <div key={label} style={{ textAlign: 'center' }}>
            <div style={{
              fontSize: 'clamp(24px, 4vw, 32px)',
              fontWeight: 900, color: '#fff',
              fontFamily: 'Georgia, serif',
              lineHeight: 1,
            }}>
              {value}
            </div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.5)', marginTop: 4, fontWeight: 500 }}>
              {label}
            </div>
          </div>
        ))}
      </motion.div>

      {/* Scroll indicator */}
      <motion.div
        animate={{ y: [0, 8, 0] }}
        transition={{ repeat: Infinity, duration: 2 }}
        style={{
          position: 'absolute', bottom: 32,
          color: 'rgba(255,255,255,0.3)',
          fontSize: 22,
        }}
      >
        ↓
      </motion.div>
    </section>
  )
}

// ─── Live flashcard demo ──────────────────────────────────────────────────────

function LiveDemo({ onCTA }) {
  const [index,   setIndex]   = useState(0)
  const [flipped, setFlipped] = useState(false)
  const word = DEMO_WORDS[index]

  const next = (knew) => {
    setFlipped(false)
    setTimeout(() => {
      setIndex(i => (i + 1) % DEMO_WORDS.length)
    }, 200)
  }

  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'var(--c-bg-off)',
    }}>
      <div style={{ maxWidth: 1100, margin: '0 auto' }}>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: 60, alignItems: 'center',
        }}>
          {/* Left — text */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <div style={{
              display: 'inline-block',
              fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
              color: 'var(--c-primary)', textTransform: 'uppercase',
              background: 'var(--c-primary-pale)',
              padding: '4px 12px', borderRadius: 99, marginBottom: 16,
            }}>
              Try it now
            </div>
            <h2 style={{
              fontSize: 'clamp(28px, 4vw, 42px)',
              fontWeight: 900, color: 'var(--c-text)',
              fontFamily: 'Georgia, serif',
              lineHeight: 1.2, letterSpacing: '-0.5px',
              marginBottom: 16,
            }}>
              Learn smarter,<br />not harder.
            </h2>
            <p style={{
              fontSize: 16, color: 'var(--c-text-muted)',
              lineHeight: 1.7, marginBottom: 24, maxWidth: 400,
            }}>
              Flip the card to reveal the definition. Rate yourself honestly —
              our algorithm handles the rest, bringing back words you struggle with more often.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                '✓ Flip to reveal definition',
                '✓ Rate Easy or Hard',
                '✓ AI-powered memory tricks',
                '✓ Track mastery 0→100',
              ].map(item => (
                <div key={item} style={{
                  display: 'flex', alignItems: 'center', gap: 10,
                  fontSize: 14, color: 'var(--c-text)',
                }}>
                  <span style={{ color: 'var(--c-success)', fontWeight: 700 }}>
                    {item.slice(0, 1)}
                  </span>
                  {item.slice(2)}
                </div>
              ))}
            </div>
          </motion.div>

          {/* Right — interactive card */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            {/* Card */}
            <div
              onClick={() => setFlipped(f => !f)}
              style={{
                background: '#fff',
                border: '1.5px solid var(--c-border)',
                borderRadius: 20,
                padding: '32px 28px',
                minHeight: 280,
                cursor: 'pointer',
                boxShadow: '0 8px 40px rgba(139,26,46,0.08)',
                display: 'flex', flexDirection: 'column',
                justifyContent: 'center',
                marginBottom: 16,
                position: 'relative',
                overflow: 'hidden',
                transition: 'box-shadow 0.2s ease',
              }}
            >
              {/* Decorative corner */}
              <div style={{
                position: 'absolute', top: -20, right: -20,
                width: 100, height: 100, borderRadius: '50%',
                background: 'var(--c-primary-pale)',
              }} />

              <div style={{
                position: 'absolute', top: 14, right: 14,
                fontSize: 10, fontWeight: 600,
                color: 'var(--c-text-muted)',
              }}>
                {flipped ? 'Definition' : 'Tap to flip'}
              </div>

              <AnimatePresence mode="wait">
                {!flipped ? (
                  <motion.div
                    key="front"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.15 }}
                  >
                    <div style={{
                      fontSize: 11, fontWeight: 600, letterSpacing: '0.08em',
                      color: 'var(--c-primary)', textTransform: 'uppercase',
                      marginBottom: 10,
                    }}>
                      {word.part}
                    </div>
                    <div style={{
                      fontSize: 36, fontWeight: 900,
                      color: 'var(--c-text)',
                      fontFamily: 'Georgia, serif',
                      letterSpacing: '-0.5px',
                      marginBottom: 8,
                    }}>
                      {word.word}
                    </div>
                    <div style={{ fontSize: 15, color: 'var(--c-text-muted)' }}>
                      {word.pronunciation}
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="back"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.15 }}
                  >
                    <p style={{
                      fontSize: 17, color: 'var(--c-text)',
                      lineHeight: 1.65, marginBottom: 14,
                    }}>
                      {word.definition}
                    </p>
                    <p style={{
                      fontSize: 13, color: 'var(--c-text-muted)',
                      fontStyle: 'italic', lineHeight: 1.5, marginBottom: 14,
                    }}>
                      "{word.example}"
                    </p>
                    <div style={{
                      background: 'var(--c-gold-pale)',
                      border: '1px solid var(--c-gold-light)',
                      borderRadius: 10, padding: '10px 12px',
                    }}>
                      <span style={{ fontSize: 12, color: 'var(--c-gold)', fontWeight: 600 }}>
                        💡 {word.mnemonic}
                      </span>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Rating buttons */}
            <AnimatePresence>
              {flipped && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  style={{ display: 'flex', gap: 10 }}
                >
                  <button
                    onClick={() => next(false)}
                    style={{
                      flex: 1, minHeight: 48,
                      background: 'var(--c-danger-pale)',
                      color: 'var(--c-danger)',
                      border: '1.5px solid var(--c-danger)',
                      borderRadius: 12, fontSize: 15, fontWeight: 600,
                      cursor: 'pointer',
                    }}
                  >
                    😕 Hard
                  </button>
                  <button
                    onClick={() => next(true)}
                    style={{
                      flex: 1, minHeight: 48,
                      background: 'var(--c-success-pale)',
                      color: 'var(--c-success)',
                      border: '1.5px solid var(--c-success)',
                      borderRadius: 12, fontSize: 15, fontWeight: 600,
                      cursor: 'pointer',
                    }}
                  >
                    😊 Easy
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Word counter */}
            <div style={{
              display: 'flex', justifyContent: 'center', gap: 6, marginTop: 16,
            }}>
              {DEMO_WORDS.map((_, i) => (
                <div key={i} style={{
                  width: i === index ? 20 : 6, height: 6,
                  borderRadius: 3,
                  background: i === index ? 'var(--c-primary)' : 'var(--c-border)',
                  transition: 'all 0.3s ease',
                }} />
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}

// ─── How it works ─────────────────────────────────────────────────────────────

function HowItWorks({ onCTA }) {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: '#fff',
    }}>
      <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div style={{
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
            color: 'var(--c-primary)', textTransform: 'uppercase',
            marginBottom: 12,
          }}>
            How it works
          </div>
          <h2 style={{
            fontSize: 'clamp(28px, 4vw, 44px)',
            fontWeight: 900, color: 'var(--c-text)',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-0.5px', lineHeight: 1.2,
            marginBottom: 60,
          }}>
            Three steps to a higher score.
          </h2>
        </motion.div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          gap: 32,
        }}>
          {STEPS.map(({ num, title, desc }, i) => (
            <motion.div
              key={num}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              style={{
                textAlign: 'left',
                padding: '28px',
                background: 'var(--c-bg-off)',
                borderRadius: 20,
                border: '1px solid var(--c-border)',
                position: 'relative',
                overflow: 'hidden',
              }}
            >
              <div style={{
                position: 'absolute', top: -10, right: -10,
                fontSize: 80, fontWeight: 900,
                color: 'rgba(139,26,46,0.05)',
                fontFamily: 'Georgia, serif',
                lineHeight: 1,
                pointerEvents: 'none',
              }}>
                {num}
              </div>
              <div style={{
                fontSize: 13, fontWeight: 800, color: 'var(--c-primary)',
                marginBottom: 12, fontFamily: 'Georgia, serif',
              }}>
                {num}
              </div>
              <div style={{
                fontSize: 20, fontWeight: 700, color: 'var(--c-text)',
                marginBottom: 10, lineHeight: 1.2,
              }}>
                {title}
              </div>
              <div style={{
                fontSize: 14, color: 'var(--c-text-muted)',
                lineHeight: 1.65,
              }}>
                {desc}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Features ─────────────────────────────────────────────────────────────────

function Features() {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'var(--c-bg-off)',
    }}>
      <div style={{ maxWidth: 1100, margin: '0 auto' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          style={{ textAlign: 'center', marginBottom: 60 }}
        >
          <div style={{
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
            color: 'var(--c-primary)', textTransform: 'uppercase',
            marginBottom: 12,
          }}>
            Features
          </div>
          <h2 style={{
            fontSize: 'clamp(28px, 4vw, 44px)',
            fontWeight: 900, color: 'var(--c-text)',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-0.5px', lineHeight: 1.2,
          }}>
            Everything you need.<br />Nothing you don't.
          </h2>
        </motion.div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: 20,
        }}>
          {FEATURES.map(({ icon, title, desc, color }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.07 }}
              whileHover={{ y: -3, boxShadow: '0 12px 40px rgba(0,0,0,0.08)' }}
              style={{
                background: '#fff',
                border: '1px solid var(--c-border)',
                borderRadius: 20,
                padding: '28px',
                cursor: 'default',
                transition: 'box-shadow 0.2s ease',
              }}
            >
              <div style={{
                width: 52, height: 52, borderRadius: 14,
                background: color === '#8b1a2e'
                  ? 'var(--c-primary-pale)'
                  : color === '#c9963a'
                  ? 'var(--c-gold-pale)'
                  : 'var(--c-success-pale)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 26, marginBottom: 16,
              }}>
                {icon}
              </div>
              <div style={{
                fontSize: 17, fontWeight: 700, color: 'var(--c-text)',
                marginBottom: 8,
              }}>
                {title}
              </div>
              <div style={{
                fontSize: 14, color: 'var(--c-text-muted)',
                lineHeight: 1.65,
              }}>
                {desc}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Final CTA ────────────────────────────────────────────────────────────────

function FinalCTA({ onCTA }) {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'linear-gradient(160deg, #3d0a15 0%, #8b1a2e 60%, #5c111e 100%)',
      textAlign: 'center',
      position: 'relative', overflow: 'hidden',
    }}>
      <div style={{
        position: 'absolute', top: -60, left: '50%',
        transform: 'translateX(-50%)',
        width: 600, height: 600, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(201,150,58,0.12) 0%, transparent 65%)',
        pointerEvents: 'none',
      }} />

      <div style={{ maxWidth: 600, margin: '0 auto', position: 'relative' }}>
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div style={{ fontSize: 52, marginBottom: 20 }}>🏆</div>
          <h2 style={{
            fontSize: 'clamp(30px, 5vw, 52px)',
            fontWeight: 900, color: '#fff',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-1px', lineHeight: 1.15,
            marginBottom: 16,
          }}>
            Your SAT score starts here.
          </h2>
          <p style={{
            fontSize: 17, color: 'rgba(255,255,255,0.65)',
            lineHeight: 1.7, marginBottom: 40,
          }}>
            Join students who are mastering vocabulary the smart way.
            Start free. No credit card needed.
          </p>

          <motion.button
            whileHover={{ scale: 1.05, boxShadow: '0 10px 40px rgba(201,150,58,0.5)' }}
            whileTap={{ scale: 0.97 }}
            onClick={onCTA}
            style={{
              padding: '16px 48px', minHeight: 60,
              background: 'var(--c-gold)', color: '#fff',
              border: 'none', borderRadius: 99,
              fontSize: 18, fontWeight: 800,
              cursor: 'pointer',
              boxShadow: '0 4px 24px rgba(201,150,58,0.35)',
              letterSpacing: '0.01em',
            }}
          >
            Start for free →
          </motion.button>

          <div style={{
            marginTop: 20, fontSize: 13,
            color: 'rgba(255,255,255,0.4)',
          }}>
            Free forever · No credit card
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// ─── Footer ───────────────────────────────────────────────────────────────────

function Footer() {
  return (
    <footer style={{
      background: '#1a0508',
      padding: '32px 24px',
      textAlign: 'center',
      borderTop: '1px solid rgba(255,255,255,0.06)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 12 }}>
        <div style={{
          width: 28, height: 28, borderRadius: 8,
          background: 'var(--c-primary)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <span style={{ color: '#fff', fontWeight: 900, fontSize: 14, fontFamily: 'Georgia, serif' }}>V</span>
        </div>
        <span style={{
          fontSize: 16, fontWeight: 800, color: 'rgba(255,255,255,0.7)',
          fontFamily: 'Georgia, serif',
        }}>
          Vocabook
        </span>
      </div>
      <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>
        © 2026 Vocabook. Built for SAT success.
      </div>
    </footer>
  )
}

// ─── Landing page ─────────────────────────────────────────────────────────────

export function Landing() {
  const navigate = useNavigate()
  const handleCTA = () => navigate('/onboarding')

  return (
    <div style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }}>
      <Nav onCTA={handleCTA} />
      <Hero onCTA={handleCTA} />
      <LiveDemo onCTA={handleCTA} />
      <HowItWorks onCTA={handleCTA} />
      <Features />
      <FinalCTA onCTA={handleCTA} />
      <Footer />
    </div>
  )
}