import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import {
  BookOpen, Zap, Flame, Trophy, Users, Brain,
  ChevronDown, Check, Star, Shield, ArrowRight,
  BarChart2, Sparkles, Clock
} from 'lucide-react'

// ─── Data ─────────────────────────────────────────────────────────────────────

const DEMO_WORDS = [
  {
    word: 'Ephemeral',
    pron: '/ɪˈfem.ər.əl/',
    pos: 'adjective',
    def: 'Lasting for only a short time; transitory.',
    example: 'The ephemeral beauty of cherry blossoms makes them all the more precious.',
    mnemonic: 'Think "e-FEM-eral" — fleeting like a passing glance.',
  },
  {
    word: 'Perspicacious',
    pron: '/ˌpɜːr.spɪˈkeɪ.ʃəs/',
    pos: 'adjective',
    def: 'Having a ready insight; shrewd and discerning.',
    example: 'Her perspicacious mind spotted the flaw others had missed entirely.',
    mnemonic: 'Per-SPIC — like spectacles, you see things with extra clarity.',
  },
  {
    word: 'Recalcitrant',
    pron: '/rɪˈkæl.sɪ.trənt/',
    pos: 'adjective',
    def: 'Stubbornly resistant to authority or guidance.',
    example: 'The recalcitrant student refused every offer of help.',
    mnemonic: 'RE-calcitrant — calculates how to resist, again and again.',
  },
  {
    word: 'Sanguine',
    pron: '/ˈsæŋ.ɡwɪn/',
    pos: 'adjective',
    def: 'Optimistic, especially in difficult situations.',
    example: 'She remained sanguine despite the mounting setbacks.',
    mnemonic: 'SANG with joy — always positive, always singing.',
  },
]

const FEATURES = [
  {
    icon: Brain,
    title: 'Spaced Repetition',
    desc: 'Our algorithm surfaces words exactly when you are about to forget them — maximizing retention with minimum effort.',
    accent: '#8b1a2e',
  },
  {
    icon: Trophy,
    title: 'Boss Battles',
    desc: '10 questions. 20 seconds each. No hearts. Score 7 or more to win and claim massive XP rewards.',
    accent: '#c9963a',
  },
  {
    icon: Flame,
    title: 'Daily Streaks',
    desc: 'Build lasting habits through streaks and level up from Beginner all the way to SAT Master.',
    accent: '#1D9E75',
  },
  {
    icon: Users,
    title: 'Friend Duels',
    desc: 'Challenge friends to async vocabulary battles. Same words, different scores. May the best mind win.',
    accent: '#8b1a2e',
  },
  {
    icon: Sparkles,
    title: 'AI Mnemonics',
    desc: 'Every word gets a unique memory trick generated by AI — making even the hardest words impossible to forget.',
    accent: '#c9963a',
  },
  {
    icon: BookOpen,
    title: '1,380 Words',
    desc: 'Built from a curated SAT vocabulary book. Every word that matters, nothing that does not.',
    accent: '#1D9E75',
  },
]

const STEPS = [
  {
    num: '01',
    title: 'Set your level',
    desc: 'Take a 5-question placement test or choose your level manually. We start you exactly where you need to be.',
  },
  {
    num: '02',
    title: 'Follow the roadmap',
    desc: 'Work through structured units of 10 words each — unlocking new content as you master what comes before.',
  },
  {
    num: '03',
    title: 'Watch scores rise',
    desc: 'Track mastery word by word. Your SAT readiness score updates in real time as you conquer the vocabulary.',
  },
]

const STATS = [
  { value: '1,380+', label: 'SAT Words' },
  { value: '138',    label: 'Learning Units' },
  { value: '6',      label: 'Exercise Types' },
  { value: '100%',   label: 'Free to Start' },
]

// ─── Navbar ───────────────────────────────────────────────────────────────────

function Navbar({ onCTA }) {
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <motion.header
      initial={{ y: -70, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      style={{
        position: 'fixed',
        top: 0, left: 0, right: 0,
        zIndex: 100,
        // Full width backdrop
        background: scrolled
          ? 'rgba(255,255,255,0.75)'
          : 'transparent',
        backdropFilter: scrolled ? 'blur(16px)' : 'none',
        WebkitBackdropFilter: scrolled ? 'blur(16px)' : 'none',
        borderBottom: scrolled
          ? '1px solid rgba(139,26,46,0.1)'
          : 'none',
        transition: 'background 0.3s ease, border-color 0.3s ease, backdrop-filter 0.3s ease',
      }}
    >
      {/* Inner: max-width centered, logo in center, cta on right */}
      <div style={{
        maxWidth: 1100,
        margin: '0 auto',
        padding: '0 24px',
        height: 64,
        display: 'grid',
        gridTemplateColumns: '1fr auto 1fr',
        alignItems: 'center',
      }}>
        {/* Left — empty spacer */}
        <div />

        {/* Center — logo */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 34, height: 34,
            background: 'var(--c-primary)',
            borderRadius: 10,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 2px 8px rgba(139,26,46,0.3)',
            flexShrink: 0,
          }}>
            <span style={{
              color: '#fff', fontWeight: 900, fontSize: 17,
              fontFamily: 'Georgia, "Times New Roman", serif',
            }}>
              V
            </span>
          </div>
          <span style={{
            fontSize: 19, fontWeight: 800,
            color: scrolled ? 'var(--c-primary)' : '#fff',
            fontFamily: 'Georgia, "Times New Roman", serif',
            letterSpacing: '-0.3px',
            transition: 'color 0.3s ease',
          }}>
            Vocabook
          </span>
        </div>

        {/* Right — CTA */}
        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <motion.button
            whileTap={{ scale: 0.96 }}
            onClick={onCTA}
            style={{
              padding: '8px 20px',
              background: scrolled ? 'var(--c-primary)' : '#fff',
              color: scrolled ? '#fff' : 'var(--c-primary)',
              border: 'none', borderRadius: 99,
              fontSize: 14, fontWeight: 700,
              cursor: 'pointer',
              boxShadow: scrolled
                ? '0 2px 10px rgba(139,26,46,0.25)'
                : '0 2px 10px rgba(0,0,0,0.15)',
              transition: 'all 0.3s ease',
            }}
          >
            Get started
          </motion.button>
        </div>
      </div>
    </motion.header>
  )
}

// ─── Hero ─────────────────────────────────────────────────────────────────────

function Hero({ onCTA }) {
  const FLOATING = ['ephemeral', 'perspicacious', 'sanguine', 'recalcitrant', 'tenacious', 'lucid']

  return (
    <section style={{
      minHeight: '100vh',
      background: 'linear-gradient(160deg, #2a0710 0%, #8b1a2e 45%, #a82236 70%, #3d0a15 100%)',
      display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center',
      padding: '100px 24px 80px',
      position: 'relative', overflow: 'hidden',
      textAlign: 'center',
    }}>
      {/* Background orbs */}
      <div style={{
        position: 'absolute', top: '8%', left: '3%',
        width: 420, height: 420, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(201,150,58,0.13) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />
      <div style={{
        position: 'absolute', bottom: '8%', right: '3%',
        width: 500, height: 500, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(255,255,255,0.04) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />

      {/* Floating word chips */}
      {FLOATING.map((w, i) => (
        <motion.div
          key={w}
          initial={{ opacity: 0 }}
          animate={{ opacity: [0, 0.35, 0.35, 0], y: [20, 0, 0, -20] }}
          transition={{ duration: 4, delay: i * 0.9, repeat: Infinity, repeatDelay: 4 }}
          style={{
            position: 'absolute',
            fontSize: 11, fontWeight: 600,
            color: 'rgba(255,255,255,0.5)',
            background: 'rgba(255,255,255,0.07)',
            border: '1px solid rgba(255,255,255,0.1)',
            padding: '4px 12px', borderRadius: 99,
            top: `${14 + (i % 3) * 26}%`,
            left: i < 3 ? `${2 + i * 7}%` : 'auto',
            right: i >= 3 ? `${2 + (i - 3) * 7}%` : 'auto',
            pointerEvents: 'none',
          }}
        >
          {w}
        </motion.div>
      ))}

      {/* Badge */}
      <motion.div
        initial={{ opacity: 0, scale: 0.85 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2 }}
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: 'rgba(201,150,58,0.18)',
          border: '1px solid rgba(201,150,58,0.35)',
          borderRadius: 99, padding: '6px 16px', marginBottom: 28,
        }}
      >
        <Star size={13} color="#f0c96a" fill="#f0c96a" />
        <span style={{ fontSize: 13, fontWeight: 600, color: '#f0c96a' }}>
          1,380 curated SAT words
        </span>
      </motion.div>

      {/* Headline */}
      <motion.h1
        initial={{ opacity: 0, y: 28 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3, duration: 0.6 }}
        style={{
          fontSize: 'clamp(36px, 7vw, 68px)',
          fontWeight: 900, color: '#fff',
          lineHeight: 1.1, letterSpacing: '-1.5px',
          fontFamily: 'Georgia, "Times New Roman", serif',
          marginBottom: 20, maxWidth: 780,
        }}
      >
        Master every word
        <br />
        <span style={{
          WebkitTextStroke: '2px rgba(255,255,255,0.55)',
          color: 'transparent',
        }}>
          before test day.
        </span>
      </motion.h1>

      {/* Subheadline */}
      <motion.p
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.42 }}
        style={{
          fontSize: 'clamp(15px, 2.2vw, 19px)',
          color: 'rgba(255,255,255,0.68)',
          maxWidth: 500, lineHeight: 1.72,
          marginBottom: 40,
        }}
      >
        The gamified vocabulary app built for SAT prep.
        Spaced repetition, boss battles, and AI mnemonics —
        so nothing slips through the cracks.
      </motion.p>

      {/* CTAs */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.54 }}
        style={{ display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center' }}
      >
        <motion.button
          whileHover={{ scale: 1.03, boxShadow: '0 8px 30px rgba(201,150,58,0.45)' }}
          whileTap={{ scale: 0.97 }}
          onClick={onCTA}
          style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '14px 36px', minHeight: 54,
            background: 'var(--c-gold)', color: '#fff',
            border: 'none', borderRadius: 99,
            fontSize: 16, fontWeight: 800, cursor: 'pointer',
            boxShadow: '0 4px 20px rgba(201,150,58,0.35)',
            letterSpacing: '0.01em',
          }}
        >
          Start for free
          <Zap size={16} fill="#fff" color="#fff" />
        </motion.button>

        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={onCTA}
          style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '14px 28px', minHeight: 54,
            background: 'rgba(255,255,255,0.09)',
            color: '#fff',
            border: '1.5px solid rgba(255,255,255,0.28)',
            borderRadius: 99, fontSize: 15, fontWeight: 600,
            cursor: 'pointer',
          }}
        >
          <BookOpen size={16} />
          Log in
        </motion.button>
      </motion.div>

      {/* Stats */}
      <motion.div
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.68 }}
        style={{
          display: 'flex', gap: 'clamp(20px, 5vw, 52px)',
          marginTop: 64, flexWrap: 'wrap', justifyContent: 'center',
        }}
      >
        {STATS.map(({ value, label }) => (
          <div key={label} style={{ textAlign: 'center' }}>
            <div style={{
              fontSize: 'clamp(22px, 3.5vw, 30px)',
              fontWeight: 900, color: '#fff',
              fontFamily: 'Georgia, serif', lineHeight: 1,
            }}>
              {value}
            </div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.45)', marginTop: 5, fontWeight: 500 }}>
              {label}
            </div>
          </div>
        ))}
      </motion.div>

      {/* Scroll hint */}
      <motion.div
        animate={{ y: [0, 7, 0] }}
        transition={{ repeat: Infinity, duration: 2.2 }}
        style={{ position: 'absolute', bottom: 30 }}
      >
        <ChevronDown size={22} color="rgba(255,255,255,0.28)" />
      </motion.div>
    </section>
  )
}

// ─── Interactive flashcard demo ───────────────────────────────────────────────

function FlashcardDemo() {
  const [index,   setIndex]   = useState(0)
  const [flipped, setFlipped] = useState(false)
  const word = DEMO_WORDS[index]

  const next = () => {
    setFlipped(false)
    setTimeout(() => setIndex(i => (i + 1) % DEMO_WORDS.length), 200)
  }

  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'var(--c-bg-off)',
    }}>
      <div style={{
        maxWidth: 1100, margin: '0 auto',
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
        gap: 60, alignItems: 'center',
      }}>
        {/* Left — text */}
        <motion.div
          initial={{ opacity: 0, x: -24 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.55 }}
        >
          <div style={{
            display: 'inline-block',
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
            color: 'var(--c-primary)', textTransform: 'uppercase',
            background: 'var(--c-primary-pale)',
            padding: '4px 12px', borderRadius: 99, marginBottom: 16,
          }}>
            Try it now
          </div>

          <h2 style={{
            fontSize: 'clamp(26px, 3.5vw, 40px)',
            fontWeight: 900, color: 'var(--c-text)',
            fontFamily: 'Georgia, serif',
            lineHeight: 1.2, letterSpacing: '-0.5px', marginBottom: 16,
          }}>
            Learn smarter,<br />not harder.
          </h2>

          <p style={{
            fontSize: 15, color: 'var(--c-text-muted)',
            lineHeight: 1.72, marginBottom: 24, maxWidth: 400,
          }}>
            Flip the card to reveal the definition. Rate yourself honestly —
            our algorithm handles the rest, bringing back words you struggle
            with more often.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { icon: Check, text: 'Flip to reveal definition' },
              { icon: Check, text: 'I Know or I Don\'t Know — no pressure' },
              { icon: Check, text: 'AI-powered memory tricks included' },
              { icon: Check, text: 'Mastery tracked from 0 to 100' },
            ].map(({ icon: Icon, text }) => (
              <div key={text} style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 14, color: 'var(--c-text)' }}>
                <div style={{
                  width: 20, height: 20, borderRadius: '50%', flexShrink: 0,
                  background: 'var(--c-success-pale)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <Icon size={11} color="var(--c-success)" strokeWidth={2.5} />
                </div>
                {text}
              </div>
            ))}
          </div>
        </motion.div>

        {/* Right — flashcard */}
        <motion.div
          initial={{ opacity: 0, x: 24 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.55, delay: 0.1 }}
        >
          {/* 3D flip card */}
          <div
            onClick={() => setFlipped(f => !f)}
            style={{
              perspective: '1000px',
              cursor: 'pointer',
              marginBottom: 14,
              userSelect: 'none',
            }}
          >
            <motion.div
              animate={{ rotateY: flipped ? 180 : 0 }}
              transition={{ duration: 0.45, ease: [0.4, 0, 0.2, 1] }}
              style={{
                transformStyle: 'preserve-3d',
                position: 'relative',
                height: 280,
                borderRadius: 20,
              }}
            >
              {/* Front */}
              <div style={{
                position: 'absolute', inset: 0,
                backfaceVisibility: 'hidden',
                WebkitBackfaceVisibility: 'hidden',
                background: '#fff',
                border: '1px solid var(--c-border)',
                borderRadius: 20,
                padding: '28px 24px',
                display: 'flex', flexDirection: 'column',
                alignItems: 'center', justifyContent: 'center',
                textAlign: 'center',
                boxShadow: '0 8px 40px rgba(139,26,46,0.08)',
              }}>
                <div style={{
                  position: 'absolute', top: -18, right: -18,
                  width: 90, height: 90, borderRadius: '50%',
                  background: 'var(--c-primary-pale)', pointerEvents: 'none',
                }} />
                <div style={{ fontSize: 11, color: 'var(--c-text-muted)', marginBottom: 14, letterSpacing: '0.06em', textTransform: 'uppercase' }}>
                  Tap to reveal
                </div>
                <div style={{ fontSize: 'clamp(26px, 5vw, 34px)', fontWeight: 900, color: 'var(--c-text)', fontFamily: 'Georgia, serif', letterSpacing: '-0.5px', marginBottom: 8 }}>
                  {word.word}
                </div>
                <div style={{ fontSize: 14, color: 'var(--c-text-muted)', marginBottom: 4 }}>
                  {word.pron}
                </div>
                <div style={{ fontSize: 12, color: 'var(--c-primary)', fontWeight: 600 }}>
                  {word.pos}
                </div>
              </div>

              {/* Back */}
              <div style={{
                position: 'absolute', inset: 0,
                backfaceVisibility: 'hidden',
                WebkitBackfaceVisibility: 'hidden',
                transform: 'rotateY(180deg)',
                background: '#fff',
                border: '1px solid var(--c-border)',
                borderRadius: 20,
                padding: '24px',
                display: 'flex', flexDirection: 'column',
                justifyContent: 'center',
                boxShadow: '0 8px 40px rgba(139,26,46,0.08)',
                overflow: 'hidden',
              }}>
                <p style={{ fontSize: 15, color: 'var(--c-text)', lineHeight: 1.65, marginBottom: 12 }}>
                  {word.def}
                </p>
                <p style={{ fontSize: 13, color: 'var(--c-text-muted)', fontStyle: 'italic', lineHeight: 1.5, marginBottom: 12 }}>
                  "{word.example}"
                </p>
                <div style={{
                  background: 'var(--c-gold-pale)',
                  border: '1px solid var(--c-gold-light)',
                  borderRadius: 10, padding: '10px 12px',
                }}>
                  <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--c-gold)', marginBottom: 3, letterSpacing: '0.06em' }}>
                    MEMORY TRICK
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--c-text)', lineHeight: 1.5 }}>
                    {word.mnemonic}
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Rating buttons */}
          <AnimatePresence>
            {flipped && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                style={{ display: 'flex', gap: 10, marginBottom: 14 }}
              >
                <button
                  onClick={next}
                  style={{
                    flex: 1, minHeight: 46,
                    background: 'var(--c-danger-pale)',
                    color: 'var(--c-danger)',
                    border: '1.5px solid var(--c-danger)',
                    borderRadius: 12, fontSize: 14, fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                  }}
                >
                  I Don't Know
                </button>
                <button
                  onClick={next}
                  style={{
                    flex: 1, minHeight: 46,
                    background: 'var(--c-success-pale)',
                    color: 'var(--c-success)',
                    border: '1.5px solid var(--c-success)',
                    borderRadius: 12, fontSize: 14, fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                  }}
                >
                  <Check size={14} strokeWidth={2.5} />
                  I Know
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Word dots */}
          <div style={{ display: 'flex', justifyContent: 'center', gap: 6 }}>
            {DEMO_WORDS.map((_, i) => (
              <div
                key={i}
                onClick={() => { setFlipped(false); setIndex(i) }}
                style={{
                  width: i === index ? 20 : 6, height: 6,
                  borderRadius: 3, cursor: 'pointer',
                  background: i === index ? 'var(--c-primary)' : 'var(--c-border)',
                  transition: 'all 0.3s ease',
                }}
              />
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// ─── How it works ─────────────────────────────────────────────────────────────

function HowItWorks({ onCTA }) {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: '#fff',
    }}>
      <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div style={{
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
            color: 'var(--c-primary)', textTransform: 'uppercase', marginBottom: 12,
          }}>
            How it works
          </div>
          <h2 style={{
            fontSize: 'clamp(26px, 4vw, 42px)',
            fontWeight: 900, color: 'var(--c-text)',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-0.5px', lineHeight: 1.2, marginBottom: 56,
          }}>
            Three steps to a higher score.
          </h2>
        </motion.div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          gap: 24,
        }}>
          {STEPS.map(({ num, title, desc }, i) => (
            <motion.div
              key={num}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              style={{
                textAlign: 'left', padding: '28px 24px',
                background: 'var(--c-bg-off)',
                borderRadius: 20,
                border: '1px solid var(--c-border)',
                position: 'relative', overflow: 'hidden',
              }}
            >
              {/* Ghost number */}
              <div style={{
                position: 'absolute', top: -12, right: -4,
                fontSize: 76, fontWeight: 900,
                color: 'rgba(139,26,46,0.13)',
                fontFamily: 'Georgia, serif', lineHeight: 1,
                pointerEvents: 'none', userSelect: 'none',
              }}>
                {num}
              </div>

              <div style={{
                fontSize: 13, fontWeight: 800, color: 'var(--c-primary)',
                marginBottom: 12, fontFamily: 'Georgia, serif',
              }}>
                {num}
              </div>
              <div style={{ fontSize: 18, fontWeight: 700, color: 'var(--c-text)', marginBottom: 10, lineHeight: 1.2 }}>
                {title}
              </div>
              <div style={{ fontSize: 14, color: 'var(--c-text-muted)', lineHeight: 1.65 }}>
                {desc}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Features ─────────────────────────────────────────────────────────────────

function Features() {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'var(--c-bg-off)',
    }}>
      <div style={{ maxWidth: 1100, margin: '0 auto' }}>
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          style={{ textAlign: 'center', marginBottom: 56 }}
        >
          <div style={{
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
            color: 'var(--c-primary)', textTransform: 'uppercase', marginBottom: 12,
          }}>
            Features
          </div>
          <h2 style={{
            fontSize: 'clamp(26px, 4vw, 42px)',
            fontWeight: 900, color: 'var(--c-text)',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-0.5px', lineHeight: 1.2,
          }}>
            Everything you need.<br />Nothing you don't.
          </h2>
        </motion.div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: 18,
        }}>
          {FEATURES.map(({ icon: Icon, title, desc, accent }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 18 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.07 }}
              whileHover={{ y: -3, boxShadow: '0 12px 40px rgba(0,0,0,0.08)' }}
              style={{
                background: '#fff', border: '1px solid var(--c-border)',
                borderRadius: 20, padding: '26px 24px',
                transition: 'box-shadow 0.2s ease',
                cursor: 'default',
              }}
            >
              <div style={{
                width: 48, height: 48, borderRadius: 14, marginBottom: 16,
                background: accent === '#8b1a2e'
                  ? 'var(--c-primary-pale)'
                  : accent === '#c9963a'
                  ? 'var(--c-gold-pale)'
                  : 'var(--c-success-pale)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon size={22} color={accent} />
              </div>
              <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--c-text)', marginBottom: 8 }}>
                {title}
              </div>
              <div style={{ fontSize: 14, color: 'var(--c-text-muted)', lineHeight: 1.65 }}>
                {desc}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Final CTA ────────────────────────────────────────────────────────────────

function FinalCTA({ onCTA }) {
  return (
    <section style={{
      padding: 'clamp(60px, 8vw, 120px) 24px',
      background: 'linear-gradient(160deg, #2a0710 0%, #8b1a2e 55%, #3d0a15 100%)',
      textAlign: 'center',
      position: 'relative', overflow: 'hidden',
    }}>
      <div style={{
        position: 'absolute', top: -60, left: '50%',
        transform: 'translateX(-50%)',
        width: 600, height: 600, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(201,150,58,0.1) 0%, transparent 65%)',
        pointerEvents: 'none',
      }} />

      <div style={{ maxWidth: 580, margin: '0 auto', position: 'relative' }}>
        <motion.div
          initial={{ opacity: 0, y: 22 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div style={{
            width: 64, height: 64, borderRadius: 18,
            background: 'rgba(255,255,255,0.1)',
            border: '1px solid rgba(255,255,255,0.15)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            margin: '0 auto 24px',
          }}>
            <Trophy size={28} color="#f0c96a" />
          </div>

          <h2 style={{
            fontSize: 'clamp(28px, 4.5vw, 50px)',
            fontWeight: 900, color: '#fff',
            fontFamily: 'Georgia, serif',
            letterSpacing: '-1px', lineHeight: 1.15, marginBottom: 16,
          }}>
            Your SAT score starts here.
          </h2>

          <p style={{
            fontSize: 16, color: 'rgba(255,255,255,0.62)',
            lineHeight: 1.72, marginBottom: 40,
          }}>
            Join students mastering vocabulary the smart way.
            Start free. No credit card needed.
          </p>

          <motion.button
            whileHover={{ scale: 1.04, boxShadow: '0 10px 40px rgba(201,150,58,0.5)' }}
            whileTap={{ scale: 0.97 }}
            onClick={onCTA}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 10,
              padding: '16px 48px', minHeight: 58,
              background: 'var(--c-gold)', color: '#fff',
              border: 'none', borderRadius: 99,
              fontSize: 17, fontWeight: 800,
              cursor: 'pointer',
              boxShadow: '0 4px 24px rgba(201,150,58,0.35)',
              letterSpacing: '0.01em',
            }}
          >
            Start for free
            <Zap size={17} fill="#fff" color="#fff" />
          </motion.button>

          <div style={{ marginTop: 18, fontSize: 13, color: 'rgba(255,255,255,0.35)' }}>
            Free forever · No credit card
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// ─── Footer ───────────────────────────────────────────────────────────────────

function Footer() {
  return (
    <footer style={{
      background: '#100307',
      padding: '28px 24px',
      textAlign: 'center',
      borderTop: '1px solid rgba(255,255,255,0.05)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 9, marginBottom: 10 }}>
        <div style={{
          width: 26, height: 26, borderRadius: 7,
          background: 'var(--c-primary)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <span style={{ color: '#fff', fontWeight: 900, fontSize: 13, fontFamily: 'Georgia, serif' }}>V</span>
        </div>
        <span style={{
          fontSize: 15, fontWeight: 800,
          color: 'rgba(255,255,255,0.6)',
          fontFamily: 'Georgia, serif',
        }}>
          Vocabook
        </span>
      </div>
      <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.22)' }}>
        © 2025 Vocabook. Built for SAT success.
      </div>
    </footer>
  )
}

// ─── Landing ──────────────────────────────────────────────────────────────────

export function Landing() {
  const navigate = useNavigate()
  const onCTA    = () => navigate('/onboarding')

  // Landing is always light — force override dark mode CSS vars
  const lightVars = {
    '--c-bg':            '#ffffff',
    '--c-bg-off':        '#fafaf9',
    '--c-bg-subtle':     '#f5f4f2',
    '--c-text':          '#3d3c3a',
    '--c-text-muted':    '#9c9891',
    '--c-border':        '#e0ddd8',
    '--c-border-strong': '#c9c5bf',
    '--c-primary-pale':  '#f9e8eb',
    '--c-gold-pale':     '#fdf6e7',
    '--c-gold-light':    '#f0c96a',
    '--c-success-pale':  '#e1f5ee',
    '--c-danger-pale':   '#fae8e4',
  }

  return (
    <div style={{
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      background: '#ffffff',
      color: '#3d3c3a',
      ...lightVars,
    }}>
      <Navbar onCTA={onCTA} />
      <Hero onCTA={onCTA} />
      <FlashcardDemo />
      <HowItWorks onCTA={onCTA} />
      <Features />
      <FinalCTA onCTA={onCTA} />
      <Footer />
    </div>
  )
}